name: pr-test-merge-master

on:
  pull_request:
    branches:
      - developer
    paths:
      - 'lambda/**'

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Run pylint
      run: |
        pylint lambda/*.py

    - name: Run tests
      run: |
        python -m unittest discover -s lambda -p 'test_*.py'

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Merge to master
      if: success()
      run: |
        git checkout master
        git merge developer
        git push origin master
