name: pr-test-merge-master

on:
  pull_request:
    branches:
      - developer
    paths:
      - 'lambda/**'
  workflow_dispatch:

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Zip Lambda function code
      run: |
        zip -r lambda_function.zip lambda/

    - name: Update Lambda function code
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.MY_AWS_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA }}
        ZIP_FILE_PATH: 'lambda_function.zip'
      run: |
        python update_lambda_function.py

    - name: Run tests
      env:
        MY_AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
        MY_AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
      run: |
        python -m unittest discover -s lambda -p 'test_*.py'

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Accept pull request
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
        curl -s -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge \
          -d '{"commit_title":"Merging PR #${PR_NUMBER}","merge_method":"merge"}'

    - name: Merge to master
      if: success()
      run: |
        git checkout master
        git merge developer
        git push origin master
